// <auto-generated />
using System;
using BlindMatchPAS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlindMatchPAS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BlindMatchPAS.Models.ApplicationUser", b =>
            {
                b.Property<string>("Id").HasColumnType("TEXT");
                b.Property<int>("AccessFailedCount").HasColumnType("INTEGER");
                b.Property<string>("ConcurrencyStamp").HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("Email").HasMaxLength(256).HasColumnType("TEXT");
                b.Property<bool>("EmailConfirmed").HasColumnType("INTEGER");
                b.Property<string>("FullName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<bool>("LockoutEnabled").HasColumnType("INTEGER");
                b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("TEXT");
                b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("TEXT");
                b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("TEXT");
                b.Property<string>("PasswordHash").HasColumnType("TEXT");
                b.Property<string>("PhoneNumber").HasColumnType("TEXT");
                b.Property<bool>("PhoneNumberConfirmed").HasColumnType("INTEGER");
                b.Property<string>("Role").IsRequired().HasColumnType("TEXT");
                b.Property<string>("SecurityStamp").HasColumnType("TEXT");
                b.Property<bool>("TwoFactorEnabled").HasColumnType("INTEGER");
                b.Property<string>("UserName").HasMaxLength(256).HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("AspNetUsers");
            });

            modelBuilder.Entity("BlindMatchPAS.Models.ResearchArea", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Description").IsRequired().HasMaxLength(300).HasColumnType("TEXT");
                b.Property<bool>("IsActive").HasColumnType("INTEGER");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("ResearchAreas");
                b.HasData(
                    new { Id = 1, Name = "Artificial Intelligence",  Description = "ML, Deep Learning, NLP",                  IsActive = true },
                    new { Id = 2, Name = "Web Development",           Description = "Frontend, Backend, APIs",                  IsActive = true },
                    new { Id = 3, Name = "Cybersecurity",             Description = "Network security, pen testing, cryptography", IsActive = true },
                    new { Id = 4, Name = "Cloud Computing",           Description = "AWS, Azure, GCP, DevOps",                 IsActive = true },
                    new { Id = 5, Name = "Mobile Development",        Description = "iOS, Android, cross-platform",            IsActive = true },
                    new { Id = 6, Name = "Data Science",              Description = "Analytics, visualisation, big data",      IsActive = true }
                );
            });

            modelBuilder.Entity("BlindMatchPAS.Models.Project", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Abstract").IsRequired().HasMaxLength(2000).HasColumnType("TEXT");
                b.Property<bool>("IdentityRevealed").HasColumnType("INTEGER");
                b.Property<DateTime?>("MatchedAt").HasColumnType("TEXT");
                b.Property<int>("ResearchAreaId").HasColumnType("INTEGER");
                b.Property<int>("Status").HasColumnType("INTEGER");
                b.Property<DateTime>("SubmittedAt").HasColumnType("TEXT");
                b.Property<string>("StudentId").IsRequired().HasColumnType("TEXT");
                b.Property<string>("SupervisorId").HasColumnType("TEXT");
                b.Property<string>("TechStack").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Projects");
            });

            modelBuilder.Entity("BlindMatchPAS.Models.SupervisorExpertise", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int>("ResearchAreaId").HasColumnType("INTEGER");
                b.Property<string>("SupervisorId").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("SupervisorExpertise");
            });

            modelBuilder.Entity("BlindMatchPAS.Models.SupervisorInterest", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("ExpressedAt").HasColumnType("TEXT");
                b.Property<int>("ProjectId").HasColumnType("INTEGER");
                b.Property<string>("SupervisorId").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex(new[] { "SupervisorId", "ProjectId" }, name: "IX_SupervisorInterests_SupervisorId_ProjectId").IsUnique();
                b.ToTable("SupervisorInterests");
            });
#pragma warning restore 612, 618
        }
    }
}
